# Generated by Django 3.2.2 on 2021-05-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photo/default.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photo/default.jpg', upload_to='menu/photo/'),
        ),
    ]
