# Generated by Django 3.2.2 on 2021-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmer', 'Confirmée'), ('non-confirmer', 'Non confirmée')], default='non-confirmer', max_length=20),
        ),
    ]
